### ISSUE TITLE
question: why using JS execution to pull location & dimension of an element

### ISSUE THREAD

**Issue by BogdanLivadariu** [assertthat/selenium-shutterbug#7]
regarding the implementation from [here](https://github.com/assertthat/selenium-shutterbug/blob/master/src/main/java/com/assertthat/selenium_shutterbug/utils/web/Browser.java#L153)

why do you use "hard-core" JS execution, when you could simply pull the information directly from the WebElement?

```java
WebElement el;
el.getLocation(); // returns a Point
el.getSize(); // returns a Dimension

    public Coordinates getBoundingClientRect(WebElement element) {
        return new Coordinates(element.getLocation(), element.getSize());
    }
```

**Comment by inha-briia** [comment]
Hi Bogdan,

Yes, you are right. We could have used el.getSize(); here. 

Its more tricky with el.getLocation(); though, it returns absolute coordinated of an element on the page, while using JS element.getBoundingClientRect(); returns location relatively to the view port.

Since the current version of Shutterbug does not support making screenshot of an element which is outside of the view port, we need to locate the element using relative coordinates. 

We are planning to add the feature of screenshotting the element which is located outside the view port in the next release and so use the code you have suggested.

Thanks,
Inha
